name: Tests & Lint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8 mypy  # Устанавливаем линтеры один раз

      - name: Save virtual environment
        uses: actions/upload-artifact@v4
        with:
          name: python-env
          path: venv

  tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Download virtual environment
        uses: actions/download-artifact@v4
        with:
          name: python-env
          path: venv

      - name: Activate virtual environment
        run: echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/venv" >> $GITHUB_ENV

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests/

  black:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Download virtual environment
        uses: actions/download-artifact@v4
        with:
          name: python-env
          path: venv

      - name: Activate virtual environment
        run: echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/venv" >> $GITHUB_ENV

      - name: Run black
        run: |
          source venv/bin/activate
          black --check --diff src/ tests/

  isort:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Download virtual environment
        uses: actions/download-artifact@v4
        with:
          name: python-env
          path: venv

      - name: Activate virtual environment
        run: echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/venv" >> $GITHUB_ENV

      - name: Run isort
        run: |
          source venv/bin/activate
          isort --check-only --diff src/ tests/

  flake8:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Download virtual environment
        uses: actions/download-artifact@v4
        with:
          name: python-env
          path: venv

      - name: Activate virtual environment
        run: echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/venv" >> $GITHUB_ENV

      - name: Run flake8
        run: |
          source venv/bin/activate
          flake8 src/ tests/

  mypy:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Download virtual environment
        uses: actions/download-artifact@v4
        with:
          name: python-env
          path: venv

      - name: Activate virtual environment
        run: echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/venv" >> $GITHUB_ENV

      - name: Run mypy
        run: |
          source venv/bin/activate
          mypy src/ tests/
